### ISSUE TITLE
An OVE scheduler to provide application URL instead of end user providing it

### ISSUE THREAD

**Issue by dsigdosystem** [ove/ove#1]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [senakafdo](https://github.com/senakafdo)**
_Wednesday Sep 12, 2018 at 21:35 GMT_
_Originally opened as https://github.com/dsi-icl/ove/issues/22_

----

Current syntax for creating a section includes `{"url": "OVE_APP_URL"}`. All API users therefore will have to make an educated guess on what URL to provide if an app was running at multiple locations. This is tedious to manage and also possibly redundant - reasons below.

Each app is fully aware of the/a OVE URL (depending on whether there is a LB in front of the cluster or not) when it boots up. So, the apps themselves can register with OVE and OVE can revalidate the registrations to ensure app instances are up and running. Since all apps and OVE share a common messaging infrastructure a periodic broadcast from OVE requesting a "let me know who exists" is easily possible. Therefore, all that is required at the point of creating the section is to provide the name/type of an app. 

Pros:
- OVE can return a URL from a pool of URLs that are available for each type of app.
- Highly available design, since OVE even gets the freedom (via the use of some good algorithm) to decide on allocating an application instance for a given section.
- Application instances can support a model of warm standby and delay announcing their availability until a certain condition is met (good for containerised deployments).

Cons:
 - The control endpoint will no longer be static, and it will be mandatory to parse the response of the API call to determine its location.
 - Each app will have to inform OVE its publicly visible URL, which will introduce an additional configuration parameter during bootup.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/jamesscottbrown"><img src="https://avatars1.githubusercontent.com/u/338833?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jamesscottbrown](https://github.com/jamesscottbrown)**
_Thursday Sep 13, 2018 at 10:25 GMT_

----

Is it expected that apps will be "running at multiple locations" or that there will be "a pool of URLs" available for each app?

This introduces additional complexity, and I don't know if it is necessary.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Thursday Sep 13, 2018 at 10:46 GMT_

----

I agree on the additional complexity and hence these pros and cons.

So, from an OVE core point of view we considered the fact of having multiple app BEs to be a feature, originally. The design of the messaging model, isolation of state etc was all based on that.

However, I can confirm that all current requirements of DSI and potentially most future requirements of the DSI will not need more than one backend per type of app. Each BE is reliable (in the sense PM2 ensures recovery).

But, the conflict of interest here is that OVE is both a research project and also a tool used in production. For extreme research use cases it is crucial that we have very high scalability of the app BEs.

May I therefore propose a compromise:
(a) The creation of a section accepts a URL, using which OVE core will create the section at the designated endpoint of the App.
(b) The creation of a section accepts a type/name of an app, and at point of creating a section OVE will use a pre-registered endpoint.
This would enable both usecases.

Note: Having independent BEs for each type of app is different and a mandatory requirement and is therefore supported as standard.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/jamesscottbrown"><img src="https://avatars1.githubusercontent.com/u/338833?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jamesscottbrown](https://github.com/jamesscottbrown)**
_Thursday Sep 13, 2018 at 11:53 GMT_

----

I've thought about this a little more and I think there are two possible reasons why someone might want multiple app servers for the same app type:

* for reliability, in case one app server goes down
* for scalability, if more sections use the same app than can be served by a single server

However, in the first case, the sections attached to the failed server would need to be deleted and replaced by new sections attached to a working server. In the second case, the user may well want each server to serve particular sections, rather than having them assigned randomly (or by whatever OVE thinks is a good algorithm).

I thus don't think the proposal would fully handle either of these. In both cases I would probably prefer to specify the URLs for the app servers URL myself when creating sections.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Thursday Sep 13, 2018 at 15:12 GMT_

----

> However, in the first case, the sections attached to the failed server would need to be deleted and replaced by new sections attached to a working server.

Not really, because the app backing a section can be swapped by transfering the state (which is also held at the client-side) and changing the URL of iFrame. But, this was not the main intention of this issue. It was the second, because as I said PM2 ensures things to be fairly robust and if we ever find that we have lost an app, that will be a DR scenario. That can be dealt with by re-creating the section anyway and we do not need to be creative at an OVE level and complicate the code.

With regards to the second case, I don't think that human-users can be expected to be doing scheduling of app-to-section mapping. OVE does need a scheduler if we are to manage this and I wouldn't consider any alternative to be better. We had explained this on the paper as well. 

But, I have been thinking of the design in a bit more detail.

Though a scheduler is a requirement I (now) don't think it needs to be within OVE core. What we could have is a separate µService that takes care of scheduling as well as managing the availability of apps within a cluster of containers. If we make that an external µService, we have the freedom of designing that to suit our choice of deployment and the core will not be coupled to such.

So, my current view is that the scheduler is a necessary enhancement but it needs not be a part of OVE core. And, given that it is an external µService, we potentially need not make any changes to our API for creating sections.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/jamesscottbrown"><img src="https://avatars1.githubusercontent.com/u/338833?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jamesscottbrown](https://github.com/jamesscottbrown)**
_Thursday Sep 13, 2018 at 15:36 GMT_

----

> Not really, because the app backing a section can be swapped by transfering the state (which is also held at the client-side) and changing the URL of iFrame

Yes, but this requires modification of the app's view to detect that the server has gone down and transfer the state: none of the existing apps currently do this.


> With regards to the second case, I don't think that human-users can be expected to be doing scheduling of app-to-section mapping

I had meant that in the (hypothetical) case where I needed multiple app servers, I would write a script to handle the allocation (rather than doing it by hand).

> OVE does need a scheduler if we are to manage this and I wouldn't consider any alternative to be better

If the app instances are entirely independent, then this is probably true. However, if the two or more instances are visualizing the same data, I might want them to be on the same server, and an OVE scheduler wouldn't know this.

> So, my current view is that the scheduler is a necessary enhancement but it needs not be a part of OVE core. And, given that it is an external µService, we potentially need not make any changes to our API for creating sections.

I agree that a scheduler should sit outside OVE core. However, as we don't think the DSI will need it, and we're not sure any user will ever need it, I don't think it needs to be written yet.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Thursday Sep 13, 2018 at 18:19 GMT_

----

> Yes, but this requires modification of the app's view to detect that the server has gone down and transfer the state: none of the existing apps currently do this.

Not really, the container in which an application runs is directly managed by OVE.js, which can support this. But, I think that's a separate discussion and is actually not relevant here, since this issue is about something else.

> However, if the two or more instances are visualizing the same data, I might want them to be on the same server, and an OVE scheduler wouldn't know this.

Agreed, and that also makes the design of the scheduler driven by the demands of the application itself. So, the volume/location of data, the design of the application as well as the infrastructure and similar factors will influence the design of a scheduler.

> However, as we don't think the DSI will need it, and we're not sure any user will ever need it, I don't think it needs to be written yet.

The DSI's use of visualisation software is not so mature as of today. We don't intend to limit the framework to a similar scope nor we intend to limit DSI to usecase similar to what we have so far, so I believe that there may be need for it in the future. 

But, I agree with _don't think it needs to be written yet_. We better wait until we have understood the requirements fully (if they ever happen to be) and then attempt this, or else our design will be flawed to begin with. So, I agree that we park this issue for now and continue with the API that we have so far as it serves our purposes (for now).

**Comment by dsigdosystem** [comment]
<a href="https://github.com/jamesscottbrown"><img src="https://avatars1.githubusercontent.com/u/338833?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jamesscottbrown](https://github.com/jamesscottbrown)**
_Thursday Sep 13, 2018 at 19:22 GMT_

----

I think we are in agreement.

> Agreed, and that also makes the design of the scheduler driven by the demands of the application itself

This is my essential point: scheduling is application specific, so probably shouldn't be incorporated into OVE.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/davidbirchwork"><img src="https://avatars3.githubusercontent.com/u/11289564?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davidbirchwork](https://github.com/davidbirchwork)**
_Friday Sep 14, 2018 at 14:25 GMT_

----

Interesting discussion, my thoughts:

- I think that scalability of backend µServices will become important to OVE as some are quite computationally demanding. 
- Agree with the concept of fascading the endpoint url's via separate scheduling µService. 
- I wonder if a neater solution would be to enable the apps to register a scheduling policy (e.g. one service instance per section) (or even a bit of .js) with the scheduling µService. This would give us the best of both worlds.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/miguems"><img src="https://avatars3.githubusercontent.com/u/4958981?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguems](https://github.com/miguems)**
_Monday Sep 17, 2018 at 08:15 GMT_

----

Maybe this is not the place for the following comment, but I think it is related, and can be discussed in the next meeting: Are apps gonna be "limited/sandboxed" to those functionalities offered by OVE-core? Or if the developed is willing, they can bypass the offered mechanisms? In the case at hand, if OVE-core provides a scheduler, can a developer choose not to use it and implement and use its own within an app?

**Comment by dsigdosystem** [comment]
<a href="https://github.com/oserban"><img src="https://avatars1.githubusercontent.com/u/3008878?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oserban](https://github.com/oserban)**
_Monday Sep 17, 2018 at 08:34 GMT_

----

@miguems I think the answer is yes at this point and should remain the same in the future.The scheduling mechanism provided by OVE is there to help you with basic scenarios, but if it does not you can still use OVE for distributed HTML rendering and do your own custom backend.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Monday Sep 17, 2018 at 09:44 GMT_

----

@dsi-icl/ove, I think this is best discussed at a meeting. 

The last point by @davidbirchwork sounds interesting. @miguems, I believe that it would also answer your question, and I would like to point out that it will not be a part of core but a separate scheduling µService, because scheduling depends on most environment-specific factors as well.

@oserban, that can be a fallback option, but whatever we implement must be reasonably generic to avoid that option becoming a popular choice.

**Comment by jamesscottbrown** [comment]
I think we should re-examine this: I'm still not convinced of the usefulness of OVE trying to naively load-balance multiple servers for the same app, but I don't think it is reasonable to require users to remember or look up port numbers to create a section.

**Comment by oserban** [comment]
Even though the code can/should be polished a bit, basic load balancing + service selection can be done with the new auth proxy service.

**Comment by senakafdo** [comment]
Yes, this needs to be reconsidered in the context of the new proxy service(s).

**Comment by senakafdo** [comment]
The [new Loader UI](https://github.com/ove/ove-ui/tree/master/packages/ove-ui-loader) solves this problem by providing both a GUI and also providing the user with the corresponding curl commands should they wish to script the deployment of 1000s of apps into OVE.
