### ISSUE TITLE
Change clients.json to a default

### ISSUE THREAD

**Issue by DavidAkroyd** [ove/ove#10]
`ove/packages/ove-core/src/client/Clients.json` should only contain a default configuration, with the configuration for individual environments inserted upon launch.
A recommendation would be a simple 2x2, 3x3 and 4x4 grid.

**Comment by senakafdo** [comment]
The Clients.json file may have to change based on the resolution for issues #2, #7, ove/ove-docs#2 and @oserban's [dev-ls](https://github.com/ove/ove-services/tree/dev-ls) branch. Will revisit this issue once they are sorted and fix all of this in one go.

**Comment by senakafdo** [comment]
We also have another challenge in changing the clients.json when it comes to injecting it into the docker container. @oserban, do you have any thoughts on how we could have a standard Clients.json file on the Git Repo and have a deployment specific one used elsewhere?

**Comment by oserban** [comment]
We can build different docker images with different environment configuration. They can also be published on docker hub because nothing is going to be private there.

This is standard practice in the docker community when you build different versions of the same product to suit different configurations/architectures:
ove:0.1.1-generic
ove:0.1.1-gdo-prod
ove:0.1.1-gdo-dev
ove:0.1.1-local-dev

I can adapt the build script to deal with this configurations.

**Comment by DavidAkroyd** [comment]
As discussed with @oserban my preference would be to insert config at runtime, but rather than inserting a file, insert a URL to a remote hosted config. This would allow us to remain fairly generic and allow us to know which config file and server was running immediately. We could retain security on this config using IP based access rules or similar.

**Comment by senakafdo** [comment]
@DavidAkroyd, @oserban, yes I think this is the best option. We did something similar for the map layers in the maps app, we can make this the pattern for things like this.

**Comment by senakafdo** [comment]
@DavidAkroyd, the functionality now exists to load clients.json from an evironment variable. However, we also need to fix our deployment scripts (dev/prod) before we are able to change the Clients.json file to have some default values.
