### ISSUE TITLE
Avoid using 'localhost' in section creation example

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#106]
The swagger example for the creation of a section uses an [app url of `http://localhost:8084`](https://github.com/ove/ove/blob/0ee49359e998618642a9afde0a3639be4b68d792/packages/ove-core/src/server/swagger.yaml#L594).

If Swagger's "try it out" feature is used to make this API call, then OVE Core will create a section, but this will in general not be running an instance of the videos app, as this will not generally be available at `localhost`.

Ideally, this host name would be replaced in the example; if not, a comment could be added to explain that the hostname in the URL should be changed before the request is made.

**Comment by senakafdo** [comment]
Had a look into this at depth. At a very high level, this is certainly possible. 

**Approach 1**
The Swagger library we use, [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express), allows embedding of JS and CSS. It also respects YAML embedded functions using the `!!js/function` syntax. However, the Swagger UI, takes charge of the spec as soon as it is loaded and I still have not figured out how to get my functions to be called before it does its thing on the browser. 

The key to this approach would be to understand how the [page template](https://github.com/scottie1984/swagger-ui-express/blob/master/indexTemplate.html) and the [swagger-ui-init](https://github.com/scottie1984/swagger-ui-express/blob/master/swagger-ui-init.js) scripts work.

**Approach 2**
Next possibility would be to use a [Swagger plugin/preset](https://github.com/swagger-api/swagger-ui/blob/a86fcf312a0d9b04d99982bf88a3d95884eddb9a/docs/customization/overview.md#presets) which should ideally be called before the page is generated. The spec can then be modified in here. I will look further into this approach as it would be a bit cleaner than approach 1.

**Comment by senakafdo** [comment]
It is wasted effort to tweak Swagger to get this URL fixed, and it is also never going to be perfect since it is impossible to use OVE to figure out the exact URL of the OVE Videos App, as the port numbers on non-local installations may never be the standard ones, and it is also possible that OVE and the OVE Apps may not exist on the same host. Therefore I have updated the docs to inform the user that they need to fix the URL.
