### ISSUE TITLE
Deleting one section also deletes state of other sections

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#119]
Reproduction steps:
- create 2 image sections, with a state that is neither the default state nor an alternative named state
- delete one section
- after refreshing the controller for the remaining section (or opening it for the first time), it will reset and load the default state

**Comment by senakafdo** [comment]
The current API only provides an app-wide `/flush` operation which will be executed if you delete an instance of an app. This has a consequence of clearing up state for app instances across all sections. If the controllers are not reloaded, the state would be recreated for the existing sections. If the controller is reloaded, it will try to fetch the state from the app and will no longer find it.

The solution would be to introduce a section-specific `/flush/{sectionId}` operation in addition to the app-wide `/flush` operation.
