### ISSUE TITLE
[ove-lib-utils] Logger - make it service friendly

### ISSUE THREAD

**Issue by oserban** [ove/ove#13]
Currently the utils library, which includes the logger is setup to enforce the OVE style and functions. This is not generally the case for all services. 

I'd like to have the logger provided via another factory/builder (e.g. LoggerFactory), dedicated only to the logger, which will remove the Utils dependency. I think that the logger factory does not require all the setup that the Utils require anyway (e.g. setting up all the import folders, etc.)

**Comment by senakafdo** [comment]
Yes, seems like we can separate the logging from other utility functionalities. Could make the inputs of import folders etc optional, but I think still this doesn't sound quite right. A fix for this (i.e. logging-specific library) would also fix #14. I believe that there is really nothing further to fix in there (as explained on that issue).
