### ISSUE TITLE
Templates for application state/geometry

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#142]
A templating mechanism for an app's state and geometry could address several use cases:

* it would allow the use of named pixel regions (https://github.com/ove/ove-services/issues/60)

* there are certain combinations of state and geometry for the image app that are frequently repeated between presentations (e.g., every full-size native resolution image has the same geometry and state, apart from the image URL)

* there may also be repetition *within* a presentation (e.g., if a slideshow presentation loads whichever image is selected with the same settings)

**Comment by senakafdo** [comment]
This is not technically something we need to fix @ an OVE-core level, but we need to decide on how/where this would be implemented. I would be assuming this is something that needs to be provided using a service, perhaps, but it is perhaps too early to say. The key would be to formalise the structure of the `project.json` file.
