### ISSUE TITLE
Remove named states

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#143]
As currently implemented, named states are confusing or limited in several ways:

* named states can be defined within the `cached` property of the `states` property when creating a new section. However, the definition actually applies to *all* sections of the same app, not just to the section whose configuration contains the definition. Furthermore, re-defining a named state for a second section will also affect other sections (with the same app) that had previously defined it.

* the name `cached` may cause confusion, as it is only the *definition* of the state that is stored  (the corresponding data is not pre-loaded and cached by the browser, nor is it  pre-rendered in an invisible iframe)

* a named states can be used to set the state of a section/app when it is first created, but cannot be used to update a state that has already been initiated with a different state

I'm not sure that named statess are actually needed as a mechanism, and I think that templates ( #142) would be more useful.

**Comment by jamesscottbrown** [comment]
I think that *in the next OVE release*, we should allow a simplified state representation: if a state object has a `state` attribute, we should load that directly (rather than `states.load`).

This would allow the simplification of every section, from something like:

```
{
  "app": {
    "url": "http://OVE_CORE_HOST:PORT/app/svg",
    "states": {
      "load": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Trajans-Column-lower-animated.svg"
      }
    }
  },
  "space": "OVE_SPACE",
  "h": 500,
  "w": 500,
  "y": 0,
  "x": 0
}
```

to

```
{
  "app": {
    "url": "http://OVE_CORE_HOST:PORT/app/svg",
    "state": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Trajans-Column-lower-animated.svg"
    }
  },
  "space": "OVE_SPACE",
  "h": 500,
  "w": 500,
  "y": 0,
  "x": 0
}
```

We can then later deprecate `states.load` and `states.cache`.

**Comment by senakafdo** [comment]
I believe that this would create a validation challenge and also beyond that it would not be representable in Swagger. As a state could be an Object or a String. We already do support state being a string (i.e. a named 'pre-configured' state). We still have not gotten rid of the requirement of being able to configure states completely on the server and refer to them by a name. I do appreciate that `cache` is rarely used, but we frequently use `state: "foo"`.
