### ISSUE TITLE
POSTing to state without Content-Type clears state

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#151]
If a POST request is made to `APP_HOST/instances/<instance_id/state` with the header `Content-Type: application/json`, then the state is updated as expected.

However, if this header is missing, then the state is replaced by the empty object `{}`. There is no error or warning message presented to the user: the response to this request is the same as for a successful update (`{}`).

**Comment by jamesscottbrown** [comment]
It looks like this hsouild be easily fixable by adding the line:

> if (!req.is('application/json')) { res.status(415); }

to each of the request-handling methods in `packages/ove-lib-appbase/sec/index/js`.

What is happening is that the json middleware is returning an empty object as the Content-Type was not matched (as described [here](https://expressjs.com/en/api.html#express.json)).

Simialr problems might be occuring elsewehere in other OVE server components.

**Comment by senakafdo** [comment]
I have been spending time on this, today morning, and found that the following validation can be put in place

```JavaScript
    this.ensureJSON = function () {
        return function (req, res, next) {
            if (!req.is('json')) {
                const err = 'Invalid content type. This API only supports the content type: ' +
                    Constants.HTTP_CONTENT_TYPE_JSON;
                log.error(err);
                res.status(HttpStatus.UNSUPPORTED_MEDIA_TYPE).set(
                    Constants.HTTP_HEADER_CONTENT_TYPE, Constants.HTTP_CONTENT_TYPE_JSON).send(
                    req.is('*') ? JSON.stringify({ type: req.is('*') }) : this.JSON.EMPTY).end();
            } else {
                next();
            }
        };
    };
```

Thereafter this can be engaged either at a top-level for all APIs or for a specific API, as shown below:

```JavaScript
app.use(Utils.ensureJSON());

app.post('/instances/:id/state', Utils.ensureJSON(), updateStateOfSection);
```

But, it seems that the existing code/tests does not set the content-type, and in several situations it also seems that it has been developed expecting such a behaviour. So, if we are to fix this, the validation alone won't help and all code references will have to be updated as well, making it a very tedious/risky task.

However, I agree that this is something we should ideally fix as the behaviour is inconsistent. A (slightly ugly) workaround can test if the body was empty and also if the contenty-type was not set at the same time, for this specific API.

**Comment by jamesscottbrown** [comment]
Ok - we could return a 415 Error only if the Content-Type is not JSON *and* `req.body` is not empty.

If the request has no body, then it doesn't really matter what the Content-Type is.

However, if the body is not empty and the Content-Type is not JSON then the request will already fail (because the JSON middleware will replace the body with `{}`): throwing an error in this case won't break anything that isn't already broken, but will provide an explicit message to say what is wrong.

**Comment by senakafdo** [comment]
Alright, I'll go for that option then. Once done, can create a separate issue proposing the refactoring of how content types are handled and ensuring they are enforced.
