### ISSUE TITLE
API request to DELETE /sections ignores specified space name

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#168]
The API request:

```
curl --header "Content-Type: application/json" --request DELETE --data '{"space":"LocalNine"}' OVE_HOST/sections
```

unexpectedly deleted sections in all spaces, not just the specified space `LocalNine`.

The Swagger API docs state: "This operation will be limited to subset of sections if a group id or a space was provided".

**Comment by senakafdo** [comment]
@jamesscottbrown you are invoking the API wrong. See http://localhost:8080/api-docs/#/sections/delete_sections. It accepts a query parameter not a body parameter. Also, in general it is not common to pass a request body in DELETE like in POST.
