### ISSUE TITLE
`/sections` API route should return app state

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#170]
It would be very useful if the `/sections` API route included the current state of each section, by fetching this from the app: currently it displays the name of the state, and only if a named state (e.g., `Highsmith`) was loaded. 

This behaviour could be specified by a parameter (`includeStates`? `fetchStates`?), to avoid a performance impact for users who just want to know the location of spaces.

Including the actual states for each section would allow a user to easily serialise the current state of the space and save it to a `project.json` file.

**Comment by senakafdo** [comment]
Makes sense and we will have to avoid the performance impact with an additional parameter as it would need to perform an additional fetch if the full state information was required.
