### ISSUE TITLE
Graphical User Interface for OVE

### ISSUE THREAD

**Issue by senakafdo** [ove/ove#29]
Must support key features such as:
1. Laying out sections
2. Re-ordering (z-index) sections
3. Viewing of control panels

Must scale to support 1000s of apps running in parallel.

**Comment by oserban** [comment]
Happy to contribute to this

**Comment by senakafdo** [comment]
@oserban, shall we resolve this issue either once we have created corresponding issues or once we have fully implemented the requirements mentioned in the comment above?

**Comment by senakafdo** [comment]
The `load` and `preview` operations are now supported. Missing operations include being able to move, resize or re-order sections.

**Comment by oserban** [comment]
This has been moved in the UI project
