### ISSUE TITLE
[Logging] Logging fails to format a message and displays the pattern instead of the error message

### ISSUE THREAD

**Issue by oserban** [ove/ove#33]
![img_20181106_125727](https://user-images.githubusercontent.com/3008878/48067381-0ea1e580-e1c8-11e8-8915-35b5a85725ac.jpg)

**Comment by senakafdo** [comment]
I have observed the same as well. I have the feeling that this happens solely at the browser, but I have not confirmed my assumption. This happens to me when the existing visualisation was terminated and a new frame was opened in its place, and for some reason Chrome does not show the logs thereafter. I will investigate further.

**Comment by oserban** [comment]
Should we report this to the Chrome/Chromium team? Or we can close it and add it to the known issues lists

**Comment by senakafdo** [comment]
> Should we report this to the Chrome/Chromium team? Or we can close it and add it to the known issues lists

I think we can report to Chrome. Haven't done that before, will check on Monday. We can also reference that issue in here so that we can track it and resolve this.

**Comment by senakafdo** [comment]
This issue was reported on Chrome's private support channel but did not get any responses as yet. I have also raised the issue [in their forum](https://productforums.google.com/forum/#!topic/chrome/w-DpJeQxQkQ;context-place=forum/).

**Comment by senakafdo** [comment]
Google has closed the issue that I reported with no resolution. Given that there is nothing further that can be done as this is clearly a bug in Chrome and not OVE, I am resolving this issue with no fix. There is no point of working around this issue as well, and there is no better fix/implementation possible at an OVE level.
