### ISSUE TITLE
Provide support for changing the opacity of sections

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#52]
I think that it should be possible to change the opacity of a section, by sending the new opacity value as an HTTP POST request to the API route `/section/<SectionID>/opacity`.

This value should be assigned to the corresponding iFrame.

It should also be possible to assign an opacity value to a section at the time it is created, by assigning a value to an opacity attribute on the state object. 

The purpose of this is to change the opacity of overlaid content that is itself opaque, so that content underneath can be revealed or hidden. This is related to #7: both features are useful in broadly similar situations, but they are not equivalent and both should be implemented.

**Comment by DavidAkroyd** [comment]
I would second this - this would be useful when using multiple grouped sections to create overlays
