### ISSUE TITLE
Applying actions to sets of sections

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#54]
Due to the layout manager, OVE now has a notion of *groups* of sections.

The control pages for apps allow operations to be performed on individual sections. However, there is no way to simultaneously apply the same transformation to multiple groups.

For example, a `group` might contain a `network` section with a partially transparent `images` section providing annotations drawn on top. However, if the network is zoomed or panned, the image layer is unaffected, and annotations will no longer be positioned correctly relative to what they refer to.

In the first case where we encountered this problem (annotations on top of a map), we handled it by injecting the JavaScript that draws the annotation layer into the `maps` app. However, this is not necessarily the best approach, and we should think more about composing operations on a single section into operations on sets of sections.

(This is related to my previous suggestion that an OVE GUI could automatically generate a *project* control page, rather than presenting the user with the separate control pages for each section)

**Comment by senakafdo** [comment]
I think we are confusing `projects` with what is supported as stock/standard in OVE. It is expected that each project would have its own project-specific controller that is generally more capable than that of the standard controllers provided by OVE. 

There is a limit as to how much generic we can be as much as how convinient we can be at the same time. However, the design philosophy of OVE supports the concept of embedding a standard controller or a collection of standard controllers of an App within a project-specific controller. Not all controllers have been designed to support this fully. The issue ove/ove-apps#26 also has in scope an improvement to the controllers exposed by each OVE app.

I do not think that an annotation layer for the `maps` app was a wrong thing to do. Such sort of annotation layers can be developed specifically for maps. However, at the same time, I agree that this limits the possibility of designing an annotation layer that extends to `networks` and `images` apps. 

But, there is also a limit as to how generic OVE can be if we are to support such a number of requirements which may lead to lots of coupling between apps, poorer performance (and often impacting scalability) and significant complexity.

This has been approached in the pasted, tested and failed and lead to creating forks of previous frameworks to support such requirements. Therefore, we may also want to revisit what is the benefit of supporting something but also the side effects of doing it.

**Comment by senakafdo** [comment]
Also, FTR, apps tend to zoom and pan differently when driven by their corresponding controllers. This is the basis of the above explanation.

And, also I would like to add that there is the possibility of introducing annotation layers to other apps. Whether we should be doing this or not is a separate question. Similarly, OVE will also have a whiteboard app. That is intended to be an app that is spanning a number of apps beneath it rather than being an app-specific layer across individual apps. Anyway this is something related to the OVE apps repository and not something concerning OVE, at least for now.

**Comment by senakafdo** [comment]
All OVE apps that support zoom and pan can now be controlled via common zoom/pan instructions.
