### ISSUE TITLE
Section index page

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#69]
There should be a page that lists the app type and sectionId for all sections in a space, with a link to the controller page and view page for each.

This would mean users go directly to a controller page, without needing to remember which hostname/port each application is running on, or sectionIDs exist (there may be gaps if sections have been deleted, making iterating over ids from 0 inconvenient).

It could also have a link to delete a section.

**Comment by senakafdo** [comment]
I am wondering whether fixing this issue is worth compared to implementing a proper UI for OVE, as proposed in #29? I know it will make life easy, but is probably good enough only for someone to do some basic debugging. Or else we will be putting effort on implementing this page which could instead be used to fix #29. @jamesscottbrown, WDYT?

**Comment by jamesscottbrown** [comment]
I was thinking of something that would be *much* more lightweight that the full GUI (which is currently stalled, with everyone working on something else as a higher priority) , and could be implemented much more quickly. It would be very similar to the current output [returned from the `/sections` API call](https://github.com/ove/ove/blob/c11788ed556e649de3251717138a6b7acd17f3e6/packages/ove-core/src/server/api.js#L273), but formatted as an HTML page with a `<ul>` list and including a complete link to the controller (constructed by by appropriately concatenating the `APP_URL`, `control.html?oveSectionId=`, and the `sectionId` ).

The API could return either HTML or JSON from the same URL, depending on the `Accept` header of the HTTP request.

The main motivation for this is that having to remember/reconstructing the URLs for control pages is irritating.
