### ISSUE TITLE
Extract OData filtering from Networks app

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#74]
Within the Networks app, there is a function [`evaluate(node, filter)`](https://github.com/ove/ove-apps/blob/caa8b9d83199750ddbeeb044f99f228a431c3f93/packages/ove-app-networks/src/client/common/networks.js#L39), which indicates whether a particular object satisfies a filter expression written in (a subset of) OData. 

This should be extracted and made available to other apps. This would enable other apps (e.g. the HTML app) to filter the data that they display using the same expression as the networks app.

**Comment by senakafdo** [comment]
@jamesscottbrown, this is not possible to implement nor required I would suppose. 

In the HTML app, we do not have a concept of restricted OData filtering to suit what is supported by the interpreter used within the implementation of the API and also to suit the limitations of how the client-side is able to support it.

When you make code common to more than one app, you essentially create a coupling between the two apps. And, if the is never intended to work in the same way within multiple apps, you'd essentially be increasing its complexity to support more than one use of it. This will have a very negative impact on performance, which is absolutely crucial for the networks app.

At the same time, the HTML app is supposed to support displaying of a generic webpage/webapp. It is not supposed to provide you with APIs to filter content that it displays using OData etc. These are not generic requirements for this app, but rather specific requirements for someone who'd be interested in using the HTML app to display a graph/network they have drawn etc. We cannot support such a mixture of ad-hoc requirements.

I am therefore closing this issue. Please reopen only if you have a valid usecase of this and if so, please also explain your usecase in detail, and how your application would be limited to exactly the same subset of odata operations we have chosen to implement in the networks app. If you do not have such a usecase, I'd rather wait until you get to that point and look at it along the lines of 'do we really need something like this'.
